# Cloud Build configuration for cross-platform deployment
steps:
  # Build the Docker image for linux/amd64 platform
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'buildx'
      - 'build'
      - '--platform=linux/amd64'
      - '-t'
      - 'gcr.io/$PROJECT_ID/warehouse-frontend:latest'
      - '-f'
      - 'Dockerfile.simple'
      - '.'
    
  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/warehouse-frontend:latest']
    
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'warehouse-frontend'
      - '--image=gcr.io/$PROJECT_ID/warehouse-frontend:latest'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      
timeout: 1200s
options:
  machineType: 'E2_HIGHCPU_8'