# Cloud Build configuration for production deployment
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-f', 'apps/web/Dockerfile.production',
      '-t', 'gcr.io/$PROJECT_ID/warehouse-network:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/warehouse-network:latest',
      '.'
    ]
    
  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/warehouse-network:$BUILD_ID']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/warehouse-network:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'warehouse-network-app',
      '--image', 'gcr.io/$PROJECT_ID/warehouse-network:$BUILD_ID',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '2Gi',
      '--cpu', '2',
      '--timeout', '300',
      '--concurrency', '80',
      '--min-instances', '1',
      '--max-instances', '100',
      '--set-env-vars', 'NODE_ENV=production,NEXT_TELEMETRY_DISABLED=1,PORT=8080',
      '--set-env-vars', 'DATABASE_URL=postgresql://warehouse:warehouse123@34.72.74.100:5432/warehouse_network',
      '--set-env-vars', 'NEXTAUTH_URL=https://warehouse-network-app-$PROJECT_ID.us-central1.run.app',
      '--set-env-vars', 'NEXTAUTH_SECRET=production-secret-change-me-in-production'
    ]

# Store build artifacts
images:
  - 'gcr.io/$PROJECT_ID/warehouse-network:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/warehouse-network:latest'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100

# Timeout
timeout: 1200s