#!/bin/bash
# Skidspace.com Production Deployment Script
# Generated by Swarm Coordination Team - 2026-03-24

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
PROJECT_ID="${GOOGLE_CLOUD_PROJECT_ID:-skidspace-production}"
REGION="${DEPLOY_REGION:-us-central1}"
DATABASE_INSTANCE="${DB_INSTANCE_NAME:-skidspace-db-prod}"
APP_SERVICE="${APP_SERVICE_NAME:-skidspace-web}"

log() {
    echo -e "${BLUE}[$(date +'%Y-%m-%d %H:%M:%S')]${NC} $1"
}

success() {
    echo -e "${GREEN}✅ $1${NC}"
}

warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

error() {
    echo -e "${RED}❌ $1${NC}"
    exit 1
}

# Check prerequisites
check_prerequisites() {
    log "Checking deployment prerequisites..."

    # Check if required tools are installed
    command -v gcloud >/dev/null 2>&1 || error "gcloud CLI is required but not installed"
    command -v docker >/dev/null 2>&1 || error "Docker is required but not installed"
    command -v node >/dev/null 2>&1 || error "Node.js is required but not installed"
    command -v npm >/dev/null 2>&1 || error "npm is required but not installed"

    # Check if authenticated with GCP
    if ! gcloud auth list --filter="status:ACTIVE" --format="value(account)" | grep -q "@"; then
        error "Please authenticate with GCP: gcloud auth login"
    fi

    # Check if project is set
    current_project=$(gcloud config get-value project 2>/dev/null || echo "")
    if [[ "$current_project" != "$PROJECT_ID" ]]; then
        warning "Current GCP project is '$current_project', setting to '$PROJECT_ID'"
        gcloud config set project "$PROJECT_ID"
    fi

    success "Prerequisites check passed"
}

# Generate super admin credentials
generate_credentials() {
    log "Generating super admin credentials..."

    cd ../../security
    node src/super-admin-generator.js

    # Store credentials in GCP Secret Manager
    local timestamp=$(date '+%Y-%m-%d-%H-%M-%S')
    local secrets_file="config/gcp-secrets-${timestamp}.json"

    if [[ -f "$secrets_file" ]]; then
        log "Storing credentials in GCP Secret Manager..."

        # Parse and store each secret
        jq -r 'to_entries[] | "\(.key) \(.value | @base64)"' "$secrets_file" | while read -r secret_name secret_value; do
            echo "$secret_value" | base64 --decode | gcloud secrets create "$secret_name" \
                --data-file=- \
                --replication-policy="automatic" || true
        done

        # Secure cleanup
        shred -vfz "$secrets_file"
        success "Credentials stored in GCP Secret Manager"
    else
        error "Credentials file not found: $secrets_file"
    fi

    cd ../apps/web
}

# Setup database
setup_database() {
    log "Setting up production database..."

    # Check if Cloud SQL instance exists
    if ! gcloud sql instances describe "$DATABASE_INSTANCE" --region="$REGION" >/dev/null 2>&1; then
        log "Creating Cloud SQL PostgreSQL instance..."
        gcloud sql instances create "$DATABASE_INSTANCE" \
            --database-version=POSTGRES_15 \
            --tier=db-custom-2-4096 \
            --region="$REGION" \
            --storage-type=SSD \
            --storage-size=100GB \
            --storage-auto-increase \
            --backup-start-time=02:00 \
            --enable-bin-log \
            --deletion-protection \
            --require-ssl

        success "Cloud SQL instance created"
    else
        log "Cloud SQL instance already exists"
    fi

    # Create database
    gcloud sql databases create skidspace_production \
        --instance="$DATABASE_INSTANCE" || true

    # Create user
    local db_password=$(gcloud secrets versions access latest --secret="skidspace-database-credentials" | jq -r '.password')
    gcloud sql users create skidspace_prod_user \
        --instance="$DATABASE_INSTANCE" \
        --password="$db_password" || true

    success "Database setup completed"
}

# Run database migrations
run_migrations() {
    log "Running database migrations..."

    # Get database connection string
    local db_ip=$(gcloud sql instances describe "$DATABASE_INSTANCE" --format="value(ipAddresses[0].ipAddress)")
    local db_password=$(gcloud secrets versions access latest --secret="skidspace-database-credentials" | jq -r '.password')

    export DATABASE_URL="postgresql://skidspace_prod_user:${db_password}@${db_ip}:5432/skidspace_production?sslmode=require"

    # Generate Prisma client
    npm run db:generate

    # Deploy migrations
    npm run db:migrate:deploy

    # Initialize with super admin
    local init_sql_file=$(find ../../security/config -name "database-init-*.sql" | head -1)
    if [[ -f "$init_sql_file" ]]; then
        log "Initializing database with super admin..."
        psql "$DATABASE_URL" -f "$init_sql_file"
        success "Database initialized with super admin"
    else
        warning "No database initialization file found"
    fi
}

# Build and deploy application
deploy_application() {
    log "Building and deploying application..."

    # Install dependencies
    npm ci --only=production

    # Build application
    npm run build

    # Create app.yaml for GAE
    cat > app.yaml << EOF
runtime: nodejs18
service: default

env_variables:
  NODE_ENV: production

automatic_scaling:
  min_instances: 2
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

handlers:
- url: /.*
  script: auto

includes:
- .gcloudignore
EOF

    # Create .gcloudignore
    cat > .gcloudignore << EOF
.git/
.gitignore
README.md
.env*
!.env.production
node_modules/
coverage/
.nyc_output/
test/
tests/
*.test.js
*.spec.js
docs/
.next/cache/
.next/standalone/
*.md
EOF

    # Deploy to Google App Engine
    gcloud app deploy app.yaml \
        --quiet \
        --promote \
        --stop-previous-version

    success "Application deployed successfully"
}

# Configure secrets
configure_secrets() {
    log "Configuring application secrets..."

    # Update app.yaml with secret references
    cat > app.yaml << EOF
runtime: nodejs18
service: default

env_variables:
  NODE_ENV: production
  NEXTAUTH_SECRET:
    secret_id: skidspace-application-secrets
    secret_key: nextAuthSecret
  DATABASE_URL:
    secret_id: skidspace-database-credentials
    secret_key: connectionString
  SUPER_ADMIN_EMAIL:
    secret_id: skidspace-super-admin-credentials
    secret_key: email

automatic_scaling:
  min_instances: 2
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

handlers:
- url: /.*
  script: auto
EOF

    success "Secrets configured"
}

# Setup monitoring
setup_monitoring() {
    log "Setting up monitoring and alerting..."

    # Enable necessary APIs
    gcloud services enable monitoring.googleapis.com
    gcloud services enable logging.googleapis.com
    gcloud services enable clouderrorreporting.googleapis.com

    # Create uptime check
    cat > uptime-check.json << EOF
{
  "displayName": "Skidspace Production Uptime",
  "httpCheck": {
    "path": "/api/health",
    "port": 443,
    "useSsl": true
  },
  "monitoredResource": {
    "type": "uptime_url",
    "labels": {
      "project_id": "$PROJECT_ID",
      "host": "skidspace.com"
    }
  },
  "timeout": "10s",
  "period": "60s"
}
EOF

    gcloud alpha monitoring uptime-check-configs create --config-from-file=uptime-check.json

    success "Monitoring configured"
}

# Verify deployment
verify_deployment() {
    log "Verifying deployment..."

    local app_url=$(gcloud app describe --format="value(defaultHostname)")
    local health_check_url="https://$app_url/api/health"

    log "Checking application health at: $health_check_url"

    # Wait for deployment to be ready
    local attempts=0
    local max_attempts=30

    while [[ $attempts -lt $max_attempts ]]; do
        if curl -f -s "$health_check_url" >/dev/null; then
            success "Application is healthy and responding"
            break
        else
            log "Waiting for application to be ready... (attempt $((attempts + 1))/$max_attempts)"
            sleep 10
            ((attempts++))
        fi
    done

    if [[ $attempts -eq $max_attempts ]]; then
        error "Application failed to respond after $max_attempts attempts"
    fi

    # Display deployment summary
    echo ""
    echo "🎉 Deployment completed successfully!"
    echo "═══════════════════════════════════════"
    echo "🌐 Application URL: https://$app_url"
    echo "🔐 Admin Portal: https://$app_url/auth/signin"
    echo "📊 Health Check: $health_check_url"
    echo "🗄️ Database Instance: $DATABASE_INSTANCE"
    echo "☁️ GCP Project: $PROJECT_ID"
    echo "═══════════════════════════════════════"
    echo ""
    echo "Next steps:"
    echo "1. Access the admin portal with generated credentials"
    echo "2. Change the default password"
    echo "3. Enable MFA for the admin account"
    echo "4. Configure OAuth providers"
    echo "5. Set up custom domain (skidspace.com)"
    echo ""
}

# Cleanup sensitive files
cleanup() {
    log "Cleaning up sensitive files..."

    # Remove any remaining credential files
    find ../../security/config -name "*credentials*" -type f -exec shred -vfz {} \;
    find . -name "*.env*" -not -name ".env.example" -type f -exec shred -vfz {} \;

    success "Cleanup completed"
}

# Main deployment function
main() {
    echo "🚀 Starting Skidspace.com Production Deployment"
    echo "=============================================="

    check_prerequisites
    generate_credentials
    setup_database
    run_migrations
    deploy_application
    configure_secrets
    setup_monitoring
    verify_deployment
    cleanup

    success "🎉 Production deployment completed successfully!"
}

# Handle script interruption
trap cleanup EXIT

# Run main function
main "$@"