#!/bin/bash
# Skidspace.com Production Deployment Validation Script
# Generated by Swarm Coordination Team - 2026-03-24

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
ADMIN_EMAIL="admin@skidspace.com"
ADMIN_PASSWORD="l7@Z1fp,8Z!bt0*>Q17WrNt;XKUf]_qj"
BASE_URL="https://skidspace.com"
ADMIN_URL="https://admin.skidspace.com"

log() {
    echo -e "${BLUE}[$(date +'%Y-%m-%d %H:%M:%S')]${NC} $1"
}

success() {
    echo -e "${GREEN}✅ $1${NC}"
}

warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

error() {
    echo -e "${RED}❌ $1${NC}"
    return 1
}

# Test basic connectivity
test_connectivity() {
    log "Testing basic connectivity..."

    # Test main site
    if curl -f -s --max-time 10 "$BASE_URL" >/dev/null; then
        success "Main site is accessible"
    else
        error "Main site is not accessible at $BASE_URL"
    fi

    # Test admin portal
    if curl -f -s --max-time 10 "$ADMIN_URL" >/dev/null; then
        success "Admin portal is accessible"
    else
        error "Admin portal is not accessible at $ADMIN_URL"
    fi
}

# Test health endpoints
test_health_endpoints() {
    log "Testing health endpoints..."

    # Application health
    local app_health=$(curl -s --max-time 10 "$BASE_URL/api/health")
    if echo "$app_health" | grep -q '"status":"healthy"'; then
        success "Application health check passed"
    else
        error "Application health check failed: $app_health"
    fi

    # Database health
    local db_health=$(curl -s --max-time 10 "$BASE_URL/api/health/database")
    if echo "$db_health" | grep -q '"status":"healthy"'; then
        success "Database health check passed"
    else
        error "Database health check failed: $db_health"
    fi

    # Authentication health
    local auth_health=$(curl -s --max-time 10 "$BASE_URL/api/health/auth")
    if echo "$auth_health" | grep -q '"status":"healthy"'; then
        success "Authentication health check passed"
    else
        error "Authentication health check failed: $auth_health"
    fi
}

# Test authentication system
test_authentication() {
    log "Testing authentication system..."

    # Test admin login
    local login_response=$(curl -s --max-time 30 \
        -X POST "$ADMIN_URL/api/auth/signin" \
        -H "Content-Type: application/json" \
        -d '{
            "email": "'"$ADMIN_EMAIL"'",
            "password": "'"$ADMIN_PASSWORD"'",
            "tenantSlug": "platform"
        }')

    if echo "$login_response" | grep -q '"success":true\|"authenticated":true\|Set-Cookie'; then
        success "Super admin authentication works"
    else
        error "Super admin authentication failed: $login_response"
    fi

    # Test protected endpoint (should require auth)
    local protected_response=$(curl -s -w "%{http_code}" \
        --max-time 10 "$ADMIN_URL/api/admin/users")

    if [[ "$protected_response" =~ 401|403 ]]; then
        success "Protected endpoints are secured (unauthorized access blocked)"
    else
        warning "Protected endpoint validation inconclusive: HTTP $protected_response"
    fi
}

# Test database initialization
test_database() {
    log "Testing database initialization..."

    # Test user creation endpoint (should work for super admin)
    local user_test=$(curl -s --max-time 10 \
        "$BASE_URL/api/admin/users/count" \
        -H "Accept: application/json")

    if echo "$user_test" | grep -q '"count":\|"total":\|[0-9]'; then
        success "Database is initialized and accessible"
    else
        warning "Database test inconclusive: $user_test"
    fi
}

# Test security headers
test_security() {
    log "Testing security configuration..."

    # Check security headers
    local headers=$(curl -I -s --max-time 10 "$BASE_URL")

    # Check for HTTPS redirect
    if echo "$headers" | grep -q "HTTP/2 200\|HTTP/1.1 200"; then
        success "HTTPS is working correctly"
    else
        warning "HTTPS configuration may need review"
    fi

    # Check for security headers
    if echo "$headers" | grep -q "X-Frame-Options\|X-Content-Type-Options\|Strict-Transport-Security"; then
        success "Security headers are present"
    else
        warning "Some security headers may be missing"
    fi

    # Test rate limiting (make multiple requests)
    local rate_limit_test=0
    for i in {1..10}; do
        if curl -f -s --max-time 5 "$BASE_URL/api/health" >/dev/null; then
            ((rate_limit_test++))
        fi
    done

    if [[ $rate_limit_test -eq 10 ]]; then
        success "API is responding (rate limiting needs separate testing)"
    else
        warning "Some API requests failed - could indicate rate limiting or issues"
    fi
}

# Test multi-tenant features
test_multitenancy() {
    log "Testing multi-tenant configuration..."

    # Test organization endpoint
    local org_test=$(curl -s --max-time 10 \
        "$BASE_URL/api/organizations/platform")

    if echo "$org_test" | grep -q '"slug":"platform"\|"type":"PLATFORM"'; then
        success "Multi-tenant organization structure is working"
    else
        warning "Multi-tenant configuration test inconclusive: $org_test"
    fi
}

# Test environment configuration
test_environment() {
    log "Testing environment configuration..."

    # Check if we're in production mode
    local env_test=$(curl -s --max-time 10 \
        "$BASE_URL/api/health" | jq -r '.environment // "unknown"' 2>/dev/null || echo "unknown")

    if [[ "$env_test" == "production" ]]; then
        success "Application is running in production mode"
    else
        warning "Environment mode is: $env_test (should be 'production')"
    fi

    # Test that debug endpoints are not accessible
    local debug_response=$(curl -s -w "%{http_code}" \
        --max-time 10 "$BASE_URL/api/debug" -o /dev/null)

    if [[ "$debug_response" =~ 404|403 ]]; then
        success "Debug endpoints are properly secured"
    else
        warning "Debug endpoints may be accessible (HTTP $debug_response)"
    fi
}

# Performance baseline
test_performance() {
    log "Testing basic performance..."

    # Test response times
    local start_time=$(date +%s.%N)
    curl -f -s --max-time 30 "$BASE_URL" >/dev/null
    local end_time=$(date +%s.%N)
    local response_time=$(echo "$end_time - $start_time" | bc)

    if (( $(echo "$response_time < 2.0" | bc -l) )); then
        success "Response time is acceptable (${response_time}s)"
    else
        warning "Response time is slow (${response_time}s)"
    fi

    # Test API response time
    start_time=$(date +%s.%N)
    curl -f -s --max-time 30 "$BASE_URL/api/health" >/dev/null
    end_time=$(date +%s.%N)
    local api_time=$(echo "$end_time - $start_time" | bc)

    if (( $(echo "$api_time < 1.0" | bc -l) )); then
        success "API response time is good (${api_time}s)"
    else
        warning "API response time could be improved (${api_time}s)"
    fi
}

# Generate validation report
generate_report() {
    log "Generating validation report..."

    cat > /tmp/deployment-validation-report.txt << EOF
Skidspace.com Production Deployment Validation Report
Generated: $(date)
Base URL: $BASE_URL
Admin URL: $ADMIN_URL

Summary:
$(cat /tmp/validation-results.txt)

Recommendations:
1. Monitor application performance and set up alerts
2. Complete OAuth provider configuration
3. Set up custom domain with SSL certificates
4. Configure monitoring dashboards
5. Schedule regular security audits
6. Test backup and recovery procedures
7. Update admin password and enable MFA immediately

Next Steps:
1. Access admin portal: $ADMIN_URL/auth/signin
2. Login with: $ADMIN_EMAIL
3. Change default password immediately
4. Enable MFA for admin account
5. Configure production OAuth providers
6. Set up monitoring and alerting
EOF

    success "Validation report generated: /tmp/deployment-validation-report.txt"
}

# Main validation function
main() {
    echo "🔍 Starting Skidspace.com Production Deployment Validation"
    echo "========================================================"
    echo ""

    # Create temporary file for results
    echo "" > /tmp/validation-results.txt

    # Run all tests
    (test_connectivity && echo "✅ Connectivity: PASSED" || echo "❌ Connectivity: FAILED") | tee -a /tmp/validation-results.txt
    (test_health_endpoints && echo "✅ Health Checks: PASSED" || echo "❌ Health Checks: FAILED") | tee -a /tmp/validation-results.txt
    (test_authentication && echo "✅ Authentication: PASSED" || echo "❌ Authentication: FAILED") | tee -a /tmp/validation-results.txt
    (test_database && echo "✅ Database: PASSED" || echo "❌ Database: FAILED") | tee -a /tmp/validation-results.txt
    (test_security && echo "✅ Security: PASSED" || echo "❌ Security: FAILED") | tee -a /tmp/validation-results.txt
    (test_multitenancy && echo "✅ Multi-tenancy: PASSED" || echo "❌ Multi-tenancy: FAILED") | tee -a /tmp/validation-results.txt
    (test_environment && echo "✅ Environment: PASSED" || echo "❌ Environment: FAILED") | tee -a /tmp/validation-results.txt
    (test_performance && echo "✅ Performance: PASSED" || echo "❌ Performance: FAILED") | tee -a /tmp/validation-results.txt

    echo ""
    generate_report

    echo ""
    echo "🎉 Validation completed!"
    echo "📋 Check report at: /tmp/deployment-validation-report.txt"
    echo ""
    echo "🚀 Ready for production use!"
    echo "🔐 Super Admin Login: $ADMIN_URL/auth/signin"
    echo "📧 Email: $ADMIN_EMAIL"
    echo "🔑 Password: [Use generated secure password]"
    echo ""
    echo "⚠️  IMPORTANT: Change the default password immediately after login!"
}

# Run validation
main "$@"