apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: warehouse-prod
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/adebold/warehouse-network
    targetRevision: HEAD
    path: .gitops/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: warehouse-prod
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
    - ApplyOutOfSyncOnly=true
    - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas