/**
 * Authentication Service for Skidspace.com Multi-Tenant SaaS Platform
 * Handles user authentication, authorization, and session management
 * Generated by Swarm Coordination Team - 2026-03-23
 */

import { hash, compare } from "bcryptjs";
import { randomBytes, createHash } from "crypto";
import { prisma } from "@warehouse-network/db";
import { TenantService } from "./tenant-service";
import { RoleService } from "./role-service";
import { PersonaService } from "./persona-service";
import { EmailService } from "./email-service";
import { SecurityService } from "./security-service";
import { AuditService } from "./audit-service";

export interface EnhancedUserInfo {
  id: string;
  email: string;
  name?: string;
  tenantId: string;
  organization: {
    id: string;
    name: string;
    slug: string;
  };
  status: string;
  roles: Array<{
    id: string;
    name: string;
    displayName: string;
    permissions: string[];
  }>;
  personas: Array<{
    id: string;
    name: string;
    displayName: string;
    isDefault: boolean;
    isActive: boolean;
  }>;
  permissions: string[];
  activePersona?: {
    id: string;
    name: string;
    displayName: string;
  };
}

export class AuthService {
  private tenantService = new TenantService();
  private roleService = new RoleService();
  private personaService = new PersonaService();
  private emailService = new EmailService();
  private securityService = new SecurityService();
  private auditService = new AuditService();

  /**
   * Authenticate user with email and password
   */
  async authenticateWithCredentials(
    email: string,
    password: string,
    tenantSlug?: string
  ): Promise<any | null> {
    try {
      // Find user by email
      const user = await prisma.user.findUnique({
        where: { email },
        include: {
          organization: true,
          accounts: true
        }
      });

      if (!user) {
        return null;
      }

      // Check if user has a password (credentials account)
      const credentialsAccount = user.accounts.find(
        account => account.provider === "credentials"
      );

      if (!credentialsAccount || !credentialsAccount.accessToken) {
        return null;
      }

      // Verify password
      const isValidPassword = await compare(password, credentialsAccount.accessToken);
      if (!isValidPassword) {
        return null;
      }

      // Check tenant access if tenantSlug provided
      if (tenantSlug && user.organization.slug !== tenantSlug) {
        return null;
      }

      // Check if user is active
      if (user.status !== "active") {
        return null;
      }

      return {
        id: user.id,
        email: user.email,
        name: user.name,
        tenantId: user.tenantId,
        tenantSlug: user.organization.slug
      };
    } catch (error) {
      console.error("Authentication error:", error);
      return null;
    }
  }

  /**
   * Create new user with password
   */
  async createUserWithPassword(
    email: string,
    password: string,
    name: string,
    tenantId: string
  ): Promise<any> {
    try {
      // Hash password
      const hashedPassword = await hash(password, 12);

      // Create user
      const user = await prisma.user.create({
        data: {
          email,
          name,
          tenantId,
          emailVerified: null, // Will be set when email is verified
        },
        include: {
          organization: true
        }
      });

      // Create credentials account
      await prisma.account.create({
        data: {
          userId: user.id,
          type: "credentials",
          provider: "credentials",
          providerAccountId: user.id,
          accessToken: hashedPassword
        }
      });

      return user;
    } catch (error) {
      console.error("User creation error:", error);
      throw error;
    }
  }

  /**
   * Check if user has access to tenant
   */
  async checkUserTenantAccess(email: string, tenantId: string): Promise<boolean> {
    try {
      const user = await prisma.user.findUnique({
        where: { email },
        include: {
          memberships: {
            where: {
              organizationId: tenantId,
              status: "active"
            }
          }
        }
      });

      // Check if user belongs to this tenant or has cross-tenant permissions
      return user?.tenantId === tenantId || user?.memberships.length! > 0;
    } catch (error) {
      console.error("Tenant access check error:", error);
      return false;
    }
  }

  /**
   * Get enhanced user information with roles and permissions
   */
  async getEnhancedUserInfo(userId: string): Promise<EnhancedUserInfo | null> {
    try {
      const user = await prisma.user.findUnique({
        where: { id: userId },
        include: {
          organization: true,
          roles: {
            include: {
              role: {
                include: {
                  permissions: {
                    include: {
                      permission: true
                    }
                  }
                }
              }
            }
          },
          personas: {
            where: { isActive: true },
            include: {
              persona: true
            }
          },
          sessionContexts: {
            orderBy: { updatedAt: "desc" },
            take: 1,
            include: {
              activePersona: true
            }
          }
        }
      });

      if (!user) {
        return null;
      }

      // Collect all permissions from roles
      const permissions = new Set<string>();
      const roles = user.roles.map(userRole => {
        const role = userRole.role;
        const rolePermissions = role.permissions
          .filter(rp => rp.granted)
          .map(rp => rp.permission.name);

        rolePermissions.forEach(permission => permissions.add(permission));

        return {
          id: role.id,
          name: role.name,
          displayName: role.displayName,
          permissions: rolePermissions
        };
      });

      // Map personas
      const personas = user.personas.map(up => ({
        id: up.persona.id,
        name: up.persona.name,
        displayName: up.persona.displayName,
        isDefault: up.isDefault,
        isActive: up.isActive
      }));

      // Get active persona
      const activePersona = user.sessionContexts[0]?.activePersona;

      return {
        id: user.id,
        email: user.email,
        name: user.name,
        tenantId: user.tenantId,
        organization: {
          id: user.organization.id,
          name: user.organization.name,
          slug: user.organization.slug
        },
        status: user.status,
        roles,
        personas,
        permissions: Array.from(permissions),
        activePersona: activePersona ? {
          id: activePersona.id,
          name: activePersona.name,
          displayName: activePersona.displayName
        } : undefined
      };
    } catch (error) {
      console.error("Enhanced user info error:", error);
      return null;
    }
  }

  /**
   * Update user's last login time
   */
  async updateLastLogin(userId: string): Promise<void> {
    try {
      await prisma.user.update({
        where: { id: userId },
        data: {
          lastLogin: new Date(),
          loginCount: {
            increment: 1
          }
        }
      });
    } catch (error) {
      console.error("Update last login error:", error);
    }
  }

  /**
   * Update session activity
   */
  async updateSessionActivity(userId: string): Promise<void> {
    try {
      // Update session context timestamp
      await prisma.userSessionContext.updateMany({
        where: { userId },
        data: { updatedAt: new Date() }
      });
    } catch (error) {
      console.error("Session activity update error:", error);
    }
  }

  /**
   * Cleanup session context on logout
   */
  async cleanupSessionContext(userId: string): Promise<void> {
    try {
      // Remove old session contexts (older than 24 hours)
      const oneDayAgo = new Date(Date.now() - 24 * 60 * 60 * 1000);

      await prisma.userSessionContext.deleteMany({
        where: {
          userId,
          updatedAt: {
            lt: oneDayAgo
          }
        }
      });
    } catch (error) {
      console.error("Session cleanup error:", error);
    }
  }

  /**
   * Send verification email
   */
  async sendVerificationEmail(
    email: string,
    url: string,
    theme?: any
  ): Promise<void> {
    try {
      await this.emailService.sendEmailVerification({
        to: email,
        verificationUrl: url,
        theme
      });
    } catch (error) {
      console.error("Send verification email error:", error);
    }
  }

  /**
   * Send welcome email to new user
   */
  async sendWelcomeEmail(email: string, name?: string): Promise<void> {
    try {
      await this.emailService.sendWelcomeEmail({
        to: email,
        name
      });
    } catch (error) {
      console.error("Send welcome email error:", error);
    }
  }

  /**
   * Generate password reset token
   */
  async generatePasswordResetToken(email: string): Promise<string | null> {
    try {
      const user = await prisma.user.findUnique({
        where: { email }
      });

      if (!user) {
        return null;
      }

      // Generate secure token
      const token = this.securityService.generateSecureToken();
      const expires = new Date(Date.now() + 60 * 60 * 1000); // 1 hour

      // Store reset token
      await prisma.verificationToken.create({
        data: {
          identifier: email,
          token: createHash("sha256").update(token).digest("hex"),
          expires
        }
      });

      return token;
    } catch (error) {
      console.error("Password reset token generation error:", error);
      return null;
    }
  }

  /**
   * Reset user password with token
   */
  async resetPasswordWithToken(
    token: string,
    email: string,
    newPassword: string
  ): Promise<boolean> {
    try {
      const hashedToken = createHash("sha256").update(token).digest("hex");

      // Find valid token
      const verificationToken = await prisma.verificationToken.findUnique({
        where: {
          identifier_token: {
            identifier: email,
            token: hashedToken
          }
        }
      });

      if (!verificationToken || verificationToken.expires < new Date()) {
        return false;
      }

      // Hash new password
      const hashedPassword = await hash(newPassword, 12);

      // Update user's credentials account
      const user = await prisma.user.findUnique({
        where: { email },
        include: { accounts: true }
      });

      if (!user) {
        return false;
      }

      const credentialsAccount = user.accounts.find(
        account => account.provider === "credentials"
      );

      if (credentialsAccount) {
        await prisma.account.update({
          where: { id: credentialsAccount.id },
          data: { accessToken: hashedPassword }
        });
      } else {
        // Create credentials account if it doesn't exist
        await prisma.account.create({
          data: {
            userId: user.id,
            type: "credentials",
            provider: "credentials",
            providerAccountId: user.id,
            accessToken: hashedPassword
          }
        });
      }

      // Remove used token
      await prisma.verificationToken.delete({
        where: {
          identifier_token: {
            identifier: email,
            token: hashedToken
          }
        }
      });

      // Log password reset
      await this.auditService.logAuthEvent({
        eventType: "password_reset",
        userId: user.id,
        tenantId: user.tenantId,
        email
      });

      return true;
    } catch (error) {
      console.error("Password reset error:", error);
      return false;
    }
  }

  /**
   * Change user password
   */
  async changePassword(
    userId: string,
    currentPassword: string,
    newPassword: string
  ): Promise<boolean> {
    try {
      const user = await prisma.user.findUnique({
        where: { id: userId },
        include: { accounts: true }
      });

      if (!user) {
        return false;
      }

      const credentialsAccount = user.accounts.find(
        account => account.provider === "credentials"
      );

      if (!credentialsAccount || !credentialsAccount.accessToken) {
        return false;
      }

      // Verify current password
      const isValidPassword = await compare(
        currentPassword,
        credentialsAccount.accessToken
      );

      if (!isValidPassword) {
        return false;
      }

      // Hash new password
      const hashedPassword = await hash(newPassword, 12);

      // Update password
      await prisma.account.update({
        where: { id: credentialsAccount.id },
        data: { accessToken: hashedPassword }
      });

      // Log password change
      await this.auditService.logAuthEvent({
        eventType: "password_changed",
        userId: user.id,
        tenantId: user.tenantId
      });

      return true;
    } catch (error) {
      console.error("Password change error:", error);
      return false;
    }
  }

  /**
   * Check if user has specific permission
   */
  async checkUserPermission(
    userId: string,
    permission: string,
    resourceId?: string
  ): Promise<boolean> {
    try {
      const userInfo = await this.getEnhancedUserInfo(userId);
      if (!userInfo) {
        return false;
      }

      // Check if user has the permission
      const hasPermission = userInfo.permissions.includes(permission);

      // TODO: Implement resource-specific permission checks
      // if (resourceId) {
      //   // Check resource-specific permissions
      // }

      return hasPermission;
    } catch (error) {
      console.error("Permission check error:", error);
      return false;
    }
  }

  /**
   * Get user's effective permissions in current context
   */
  async getUserEffectivePermissions(
    userId: string,
    personaId?: string
  ): Promise<string[]> {
    try {
      const userInfo = await this.getEnhancedUserInfo(userId);
      if (!userInfo) {
        return [];
      }

      let effectivePermissions = [...userInfo.permissions];

      // Apply persona-specific permission overrides
      if (personaId) {
        const persona = await prisma.persona.findUnique({
          where: { id: personaId }
        });

        if (persona && persona.permissionsOverride) {
          const overrides = persona.permissionsOverride as any;
          // Apply permission overrides logic
          // This could include adding/removing specific permissions
        }
      }

      return effectivePermissions;
    } catch (error) {
      console.error("Effective permissions error:", error);
      return [];
    }
  }
}