/**
 * Persona Management Service for Skidspace.com Multi-Tenant SaaS Platform
 * Handles persona definitions, assignments, and context switching
 * Generated by Swarm Coordination Team - 2026-03-23
 */

import { prisma } from "@warehouse-network/db";
import { AuditService } from "./audit-service";

export interface PersonaDefinition {
  id: string;
  name: string;
  displayName: string;
  description?: string;
  defaultRoleId?: string;
  uiConfig: Record<string, any>;
  features: string[];
  permissionsOverride: Record<string, any>;
  color?: string;
  icon?: string;
  isSystemPersona: boolean;
  isActive: boolean;
}

export interface UserPersonaAssignment {
  personaId: string;
  userId: string;
  tenantId: string;
  isDefault: boolean;
  isActive: boolean;
  assignedAt: Date;
}

export class PersonaService {
  private auditService = new AuditService();

  /**
   * Initialize default personas for a new user
   */
  async initializeDefaultPersonas(userId: string, tenantId: string): Promise<void> {
    try {
      // Get organization to determine default personas
      const organization = await prisma.organization.findUnique({
        where: { id: tenantId },
        include: {
          personas: {
            where: {
              isSystemPersona: true,
              isActive: true
            }
          }
        }
      });

      if (!organization) {
        throw new Error(`Organization not found: ${tenantId}`);
      }

      // If no system personas exist, create default ones
      if (organization.personas.length === 0) {
        await this.createDefaultSystemPersonas(tenantId);
      }

      // Assign default persona based on user's initial role
      const user = await prisma.user.findUnique({
        where: { id: userId },
        include: {
          roles: {
            include: {
              role: true
            }
          }
        }
      });

      if (user && user.roles.length > 0) {
        // Determine appropriate default persona based on role
        const defaultPersonaName = this.determineDefaultPersona(user.roles[0].role.name);

        const defaultPersona = await prisma.persona.findFirst({
          where: {
            tenantId,
            name: defaultPersonaName,
            isActive: true
          }
        });

        if (defaultPersona) {
          await this.assignPersonaToUser(userId, defaultPersona.id, tenantId, true);
        }
      }
    } catch (error) {
      console.error("Initialize default personas error:", error);
      throw error;
    }
  }

  /**
   * Create default system personas for a tenant
   */
  async createDefaultSystemPersonas(tenantId: string): Promise<void> {
    const defaultPersonas = [
      {
        name: "super_admin",
        displayName: "Super Administrator",
        description: "Platform-wide administrative access with full system control",
        uiConfig: {
          theme: "admin",
          sidebar: "expanded",
          features: ["all"],
          dashboardLayout: "admin"
        },
        features: [
          "user_management",
          "organization_management",
          "security_management",
          "system_configuration",
          "audit_access",
          "analytics_full"
        ],
        color: "#dc2626", // Red for super admin
        icon: "shield-check",
        isSystemPersona: true
      },
      {
        name: "warehouse_partner",
        displayName: "Warehouse Partner",
        description: "Warehouse operations and partner management access",
        uiConfig: {
          theme: "warehouse",
          sidebar: "collapsed",
          features: ["warehouse", "inventory", "orders"],
          dashboardLayout: "warehouse"
        },
        features: [
          "inventory_management",
          "order_processing",
          "warehouse_operations",
          "partner_communication",
          "performance_analytics"
        ],
        color: "#059669", // Green for warehouse
        icon: "warehouse",
        isSystemPersona: true
      },
      {
        name: "customer",
        displayName: "Customer",
        description: "Customer portal access for service requests and tracking",
        uiConfig: {
          theme: "customer",
          sidebar: "minimal",
          features: ["orders", "support", "tracking"],
          dashboardLayout: "customer"
        },
        features: [
          "service_requests",
          "order_tracking",
          "communication_portal",
          "history_access",
          "support_tickets"
        ],
        color: "#2563eb", // Blue for customer
        icon: "user",
        isSystemPersona: true
      },
      {
        name: "organization_admin",
        displayName: "Organization Administrator",
        description: "Organization-level administration and user management",
        uiConfig: {
          theme: "admin",
          sidebar: "expanded",
          features: ["users", "settings", "billing"],
          dashboardLayout: "org_admin"
        },
        features: [
          "user_management",
          "permission_assignment",
          "organization_settings",
          "usage_analytics",
          "billing_management"
        ],
        color: "#7c3aed", // Purple for org admin
        icon: "users-cog",
        isSystemPersona: true
      }
    ];

    for (const personaData of defaultPersonas) {
      await prisma.persona.create({
        data: {
          ...personaData,
          tenantId,
          uiConfig: personaData.uiConfig,
          features: personaData.features,
          permissionsOverride: {}
        }
      });
    }

    await this.auditService.logEvent({
      eventType: "system_personas_created",
      tenantId,
      eventCategory: "system",
      details: { personaCount: defaultPersonas.length }
    });
  }

  /**
   * Determine default persona based on user role
   */
  private determineDefaultPersona(roleName: string): string {
    const rolePersonaMap: Record<string, string> = {
      "super_admin": "super_admin",
      "platform_admin": "super_admin",
      "warehouse_admin": "warehouse_partner",
      "warehouse_operator": "warehouse_partner",
      "customer_user": "customer",
      "org_admin": "organization_admin",
      "organization_admin": "organization_admin"
    };

    return rolePersonaMap[roleName] || "customer";
  }

  /**
   * Assign persona to user
   */
  async assignPersonaToUser(
    userId: string,
    personaId: string,
    tenantId: string,
    isDefault: boolean = false
  ): Promise<void> {
    try {
      // Check if assignment already exists
      const existingAssignment = await prisma.userPersona.findUnique({
        where: {
          userId_personaId_tenantId: {
            userId,
            personaId,
            tenantId
          }
        }
      });

      if (existingAssignment) {
        // Update existing assignment
        await prisma.userPersona.update({
          where: { id: existingAssignment.id },
          data: {
            isDefault,
            isActive: true,
            assignedAt: new Date()
          }
        });
      } else {
        // Create new assignment
        await prisma.userPersona.create({
          data: {
            userId,
            personaId,
            tenantId,
            isDefault,
            isActive: true
          }
        });
      }

      // If this is set as default, remove default from other personas for this user
      if (isDefault) {
        await prisma.userPersona.updateMany({
          where: {
            userId,
            tenantId,
            personaId: {
              not: personaId
            }
          },
          data: {
            isDefault: false
          }
        });
      }

      await this.auditService.logEvent({
        eventType: "persona_assigned",
        userId,
        tenantId,
        eventCategory: "rbac",
        details: { personaId, isDefault }
      });
    } catch (error) {
      console.error("Assign persona error:", error);
      throw error;
    }
  }

  /**
   * Switch user's active persona
   */
  async switchUserPersona(
    userId: string,
    personaId: string,
    sessionToken: string
  ): Promise<boolean> {
    try {
      // Verify user has access to this persona
      const userPersona = await prisma.userPersona.findFirst({
        where: {
          userId,
          personaId,
          isActive: true
        },
        include: {
          persona: true,
          user: true
        }
      });

      if (!userPersona) {
        return false;
      }

      // Update session context with new active persona
      await prisma.userSessionContext.upsert({
        where: {
          sessionToken
        },
        update: {
          activePersonaId: personaId,
          updatedAt: new Date()
        },
        create: {
          sessionToken,
          userId,
          tenantId: userPersona.user.tenantId,
          activePersonaId: personaId
        }
      });

      await this.auditService.logEvent({
        eventType: "persona_switched",
        userId,
        tenantId: userPersona.user.tenantId,
        eventCategory: "auth",
        details: {
          fromPersonaId: null, // Could track previous persona
          toPersonaId: personaId,
          personaName: userPersona.persona.name
        }
      });

      return true;
    } catch (error) {
      console.error("Switch persona error:", error);
      return false;
    }
  }

  /**
   * Get user's available personas
   */
  async getUserPersonas(userId: string, tenantId: string): Promise<PersonaDefinition[]> {
    try {
      const userPersonas = await prisma.userPersona.findMany({
        where: {
          userId,
          tenantId,
          isActive: true
        },
        include: {
          persona: true
        },
        orderBy: [
          { isDefault: "desc" },
          { persona: { displayName: "asc" } }
        ]
      });

      return userPersonas.map(up => ({
        id: up.persona.id,
        name: up.persona.name,
        displayName: up.persona.displayName,
        description: up.persona.description,
        defaultRoleId: up.persona.defaultRoleId,
        uiConfig: up.persona.uiConfig as Record<string, any>,
        features: up.persona.features as string[],
        permissionsOverride: up.persona.permissionsOverride as Record<string, any>,
        color: up.persona.color,
        icon: up.persona.icon,
        isSystemPersona: up.persona.isSystemPersona,
        isActive: up.isActive
      }));
    } catch (error) {
      console.error("Get user personas error:", error);
      return [];
    }
  }

  /**
   * Get user's current active persona
   */
  async getUserActivePersona(sessionToken: string): Promise<PersonaDefinition | null> {
    try {
      const sessionContext = await prisma.userSessionContext.findUnique({
        where: { sessionToken },
        include: {
          activePersona: true
        }
      });

      if (!sessionContext?.activePersona) {
        return null;
      }

      const persona = sessionContext.activePersona;
      return {
        id: persona.id,
        name: persona.name,
        displayName: persona.displayName,
        description: persona.description,
        defaultRoleId: persona.defaultRoleId,
        uiConfig: persona.uiConfig as Record<string, any>,
        features: persona.features as string[],
        permissionsOverride: persona.permissionsOverride as Record<string, any>,
        color: persona.color,
        icon: persona.icon,
        isSystemPersona: persona.isSystemPersona,
        isActive: persona.isActive
      };
    } catch (error) {
      console.error("Get active persona error:", error);
      return null;
    }
  }

  /**
   * Create custom persona for tenant
   */
  async createCustomPersona(
    tenantId: string,
    personaData: Partial<PersonaDefinition>,
    createdBy: string
  ): Promise<PersonaDefinition> {
    try {
      const persona = await prisma.persona.create({
        data: {
          tenantId,
          name: personaData.name!,
          displayName: personaData.displayName!,
          description: personaData.description,
          defaultRoleId: personaData.defaultRoleId,
          uiConfig: personaData.uiConfig || {},
          features: personaData.features || [],
          permissionsOverride: personaData.permissionsOverride || {},
          color: personaData.color,
          icon: personaData.icon,
          isSystemPersona: false,
          isActive: true
        }
      });

      await this.auditService.logEvent({
        eventType: "custom_persona_created",
        userId: createdBy,
        tenantId,
        eventCategory: "rbac",
        details: {
          personaId: persona.id,
          personaName: persona.name
        }
      });

      return {
        id: persona.id,
        name: persona.name,
        displayName: persona.displayName,
        description: persona.description,
        defaultRoleId: persona.defaultRoleId,
        uiConfig: persona.uiConfig as Record<string, any>,
        features: persona.features as string[],
        permissionsOverride: persona.permissionsOverride as Record<string, any>,
        color: persona.color,
        icon: persona.icon,
        isSystemPersona: persona.isSystemPersona,
        isActive: persona.isActive
      };
    } catch (error) {
      console.error("Create custom persona error:", error);
      throw error;
    }
  }

  /**
   * Update persona configuration
   */
  async updatePersona(
    personaId: string,
    updates: Partial<PersonaDefinition>,
    updatedBy: string
  ): Promise<PersonaDefinition | null> {
    try {
      const persona = await prisma.persona.findUnique({
        where: { id: personaId },
        include: { organization: true }
      });

      if (!persona) {
        return null;
      }

      // Don't allow updates to system personas' core properties
      if (persona.isSystemPersona) {
        // Only allow UI config and feature updates for system personas
        const allowedUpdates = {
          uiConfig: updates.uiConfig,
          features: updates.features,
          color: updates.color,
          icon: updates.icon
        };

        const updatedPersona = await prisma.persona.update({
          where: { id: personaId },
          data: {
            ...allowedUpdates,
            updatedAt: new Date()
          }
        });

        return this.mapPersonaToDefinition(updatedPersona);
      }

      // Full updates allowed for custom personas
      const updatedPersona = await prisma.persona.update({
        where: { id: personaId },
        data: {
          ...updates,
          updatedAt: new Date()
        }
      });

      await this.auditService.logEvent({
        eventType: "persona_updated",
        userId: updatedBy,
        tenantId: persona.organization?.id,
        eventCategory: "rbac",
        details: {
          personaId,
          personaName: persona.name,
          updates: Object.keys(updates)
        }
      });

      return this.mapPersonaToDefinition(updatedPersona);
    } catch (error) {
      console.error("Update persona error:", error);
      return null;
    }
  }

  /**
   * Get persona by ID
   */
  async getPersonaById(personaId: string): Promise<PersonaDefinition | null> {
    try {
      const persona = await prisma.persona.findUnique({
        where: { id: personaId }
      });

      if (!persona) {
        return null;
      }

      return this.mapPersonaToDefinition(persona);
    } catch (error) {
      console.error("Get persona by ID error:", error);
      return null;
    }
  }

  /**
   * Get all personas for a tenant
   */
  async getTenantPersonas(tenantId: string): Promise<PersonaDefinition[]> {
    try {
      const personas = await prisma.persona.findMany({
        where: {
          OR: [
            { tenantId },
            { tenantId: null, isSystemPersona: true } // Include global system personas
          ]
        },
        orderBy: [
          { isSystemPersona: "desc" },
          { displayName: "asc" }
        ]
      });

      return personas.map(this.mapPersonaToDefinition);
    } catch (error) {
      console.error("Get tenant personas error:", error);
      return [];
    }
  }

  /**
   * Check if user has access to specific features based on persona
   */
  async checkPersonaFeatureAccess(
    userId: string,
    sessionToken: string,
    feature: string
  ): Promise<boolean> {
    try {
      const activePersona = await this.getUserActivePersona(sessionToken);
      if (!activePersona) {
        return false;
      }

      return activePersona.features.includes(feature) ||
             activePersona.features.includes("all");
    } catch (error) {
      console.error("Check persona feature access error:", error);
      return false;
    }
  }

  /**
   * Map database persona to PersonaDefinition
   */
  private mapPersonaToDefinition(persona: any): PersonaDefinition {
    return {
      id: persona.id,
      name: persona.name,
      displayName: persona.displayName,
      description: persona.description,
      defaultRoleId: persona.defaultRoleId,
      uiConfig: persona.uiConfig as Record<string, any>,
      features: persona.features as string[],
      permissionsOverride: persona.permissionsOverride as Record<string, any>,
      color: persona.color,
      icon: persona.icon,
      isSystemPersona: persona.isSystemPersona,
      isActive: persona.isActive
    };
  }

  /**
   * Remove persona assignment from user
   */
  async removePersonaFromUser(
    userId: string,
    personaId: string,
    tenantId: string
  ): Promise<boolean> {
    try {
      const assignment = await prisma.userPersona.findUnique({
        where: {
          userId_personaId_tenantId: {
            userId,
            personaId,
            tenantId
          }
        }
      });

      if (!assignment) {
        return false;
      }

      // Don't allow removing the default persona
      if (assignment.isDefault) {
        throw new Error("Cannot remove default persona. Assign a different default persona first.");
      }

      await prisma.userPersona.delete({
        where: { id: assignment.id }
      });

      await this.auditService.logEvent({
        eventType: "persona_removed",
        userId,
        tenantId,
        eventCategory: "rbac",
        details: { personaId }
      });

      return true;
    } catch (error) {
      console.error("Remove persona from user error:", error);
      throw error;
    }
  }

  /**
   * Deactivate persona (soft delete)
   */
  async deactivatePersona(personaId: string, deactivatedBy: string): Promise<boolean> {
    try {
      const persona = await prisma.persona.findUnique({
        where: { id: personaId },
        include: { organization: true }
      });

      if (!persona) {
        return false;
      }

      // Don't allow deactivating system personas
      if (persona.isSystemPersona) {
        throw new Error("Cannot deactivate system personas");
      }

      await prisma.persona.update({
        where: { id: personaId },
        data: { isActive: false }
      });

      // Deactivate all user assignments
      await prisma.userPersona.updateMany({
        where: { personaId },
        data: { isActive: false }
      });

      await this.auditService.logEvent({
        eventType: "persona_deactivated",
        userId: deactivatedBy,
        tenantId: persona.organization?.id,
        eventCategory: "rbac",
        details: {
          personaId,
          personaName: persona.name
        }
      });

      return true;
    } catch (error) {
      console.error("Deactivate persona error:", error);
      throw error;
    }
  }
}