/**
 * NextAuth.js Configuration for Skidspace.com Multi-Tenant SaaS Platform
 * Generated by Swarm Coordination Team - 2026-03-23
 */

import { NextAuthOptions } from "next-auth";
import { PrismaAdapter } from "@next-auth/prisma-adapter";
import GoogleProvider from "next-auth/providers/google";
import GitHubProvider from "next-auth/providers/github";
import AzureADProvider from "next-auth/providers/azure-ad";
import EmailProvider from "next-auth/providers/email";
import CredentialsProvider from "next-auth/providers/credentials";
import { prisma } from "@warehouse-network/db";
import { AuthService } from "../services/auth-service";
import { TenantService } from "../services/tenant-service";
import { AuditService } from "../services/audit-service";
import { SecurityService } from "../services/security-service";
import { PersonaService } from "../services/persona-service";

const authService = new AuthService();
const tenantService = new TenantService();
const auditService = new AuditService();
const securityService = new SecurityService();
const personaService = new PersonaService();

export const nextAuthOptions: NextAuthOptions = {
  // Prisma adapter for database integration
  adapter: PrismaAdapter(prisma),

  // Authentication providers
  providers: [
    // Google OAuth Provider
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID!,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET!,
      authorization: {
        params: {
          prompt: "consent",
          access_type: "offline",
          response_type: "code"
        }
      }
    }),

    // GitHub OAuth Provider (for technical users)
    GitHubProvider({
      clientId: process.env.GITHUB_ID!,
      clientSecret: process.env.GITHUB_SECRET!,
      authorization: {
        params: {
          scope: "read:user user:email"
        }
      }
    }),

    // Azure AD Provider (for enterprise customers)
    AzureADProvider({
      clientId: process.env.AZURE_AD_CLIENT_ID!,
      clientSecret: process.env.AZURE_AD_CLIENT_SECRET!,
      tenantId: process.env.AZURE_AD_TENANT_ID
    }),

    // Email Provider (passwordless)
    EmailProvider({
      server: {
        host: process.env.EMAIL_SERVER_HOST,
        port: process.env.EMAIL_SERVER_PORT,
        auth: {
          user: process.env.EMAIL_SERVER_USER,
          pass: process.env.EMAIL_SERVER_PASSWORD
        }
      },
      from: process.env.EMAIL_FROM,
      sendVerificationRequest: async ({ identifier, url, provider, theme }) => {
        // Custom email verification logic
        await authService.sendVerificationEmail(identifier, url, theme);
      }
    }),

    // Credentials Provider (for email/password)
    CredentialsProvider({
      id: "credentials",
      name: "Email and Password",
      credentials: {
        email: { label: "Email", type: "email" },
        password: { label: "Password", type: "password" },
        tenantSlug: { label: "Organization", type: "text" }
      },
      async authorize(credentials, req) {
        if (!credentials?.email || !credentials?.password) {
          return null;
        }

        try {
          // Security check for suspicious activity
          const isSecure = await securityService.checkLoginSecurity(
            credentials.email,
            req.headers?.["x-forwarded-for"] as string || req.connection?.remoteAddress
          );

          if (!isSecure) {
            await auditService.logSecurityEvent({
              eventType: "suspicious_login_blocked",
              email: credentials.email,
              ipAddress: req.headers?.["x-forwarded-for"] as string,
              severity: "high"
            });
            return null;
          }

          // Authenticate user
          const user = await authService.authenticateWithCredentials(
            credentials.email,
            credentials.password,
            credentials.tenantSlug
          );

          if (user) {
            // Log successful authentication
            await auditService.logAuthEvent({
              eventType: "login_success",
              userId: user.id,
              tenantId: user.tenantId,
              provider: "credentials",
              ipAddress: req.headers?.["x-forwarded-for"] as string
            });
            return user;
          }

          // Log failed authentication
          await auditService.logAuthEvent({
            eventType: "login_failure",
            email: credentials.email,
            provider: "credentials",
            ipAddress: req.headers?.["x-forwarded-for"] as string,
            reason: "invalid_credentials"
          });

          return null;
        } catch (error) {
          console.error("Authentication error:", error);
          return null;
        }
      }
    })
  ],

  // Session configuration
  session: {
    strategy: "database",
    maxAge: 24 * 60 * 60, // 24 hours
    updateAge: 60 * 60, // 1 hour
    generateSessionToken: () => {
      // Custom secure session token generation
      return securityService.generateSecureToken();
    }
  },

  // JWT configuration (for API routes)
  jwt: {
    secret: process.env.NEXTAUTH_SECRET,
    maxAge: 24 * 60 * 60, // 24 hours
    encode: async ({ token, secret }) => {
      return await securityService.encodeJWT(token, secret);
    },
    decode: async ({ token, secret }) => {
      return await securityService.decodeJWT(token, secret);
    }
  },

  // Pages configuration
  pages: {
    signIn: "/auth/signin",
    signUp: "/auth/signup",
    signOut: "/auth/signout",
    error: "/auth/error",
    verifyRequest: "/auth/verify-request",
    newUser: "/auth/new-user"
  },

  // Callbacks for customization
  callbacks: {
    // Sign-in callback - control who can sign in
    async signIn({ user, account, profile, email, credentials }) {
      try {
        // Extract tenant information from request or email domain
        const tenantInfo = await tenantService.resolveTenantFromUser(user.email!);

        if (!tenantInfo) {
          console.log(`No tenant found for user: ${user.email}`);
          return false;
        }

        // Check if user is allowed to access this tenant
        const hasAccess = await authService.checkUserTenantAccess(
          user.email!,
          tenantInfo.id
        );

        if (!hasAccess) {
          await auditService.logSecurityEvent({
            eventType: "unauthorized_tenant_access",
            email: user.email!,
            tenantId: tenantInfo.id,
            severity: "medium"
          });
          return false;
        }

        // Store tenant information for session
        user.tenantId = tenantInfo.id;
        user.tenantSlug = tenantInfo.slug;

        // Log successful sign-in
        await auditService.logAuthEvent({
          eventType: "signin_success",
          userId: user.id,
          tenantId: tenantInfo.id,
          provider: account?.provider || "unknown"
        });

        return true;
      } catch (error) {
        console.error("Sign-in error:", error);
        return false;
      }
    },

    // Redirect callback - control where users are redirected
    async redirect({ url, baseUrl }) {
      // Parse the tenant slug from URL or session
      const urlObj = new URL(url, baseUrl);
      const tenantSlug = urlObj.searchParams.get("tenant") ||
                        urlObj.pathname.split("/")[1];

      if (tenantSlug) {
        return `${baseUrl}/${tenantSlug}/dashboard`;
      }

      // Default redirect to tenant selection
      return `${baseUrl}/select-organization`;
    },

    // Session callback - customize session object
    async session({ session, token, user }) {
      try {
        if (user) {
          // Enhance session with tenant and persona information
          const enhancedUser = await authService.getEnhancedUserInfo(user.id);

          if (enhancedUser) {
            session.user.id = enhancedUser.id;
            session.user.tenantId = enhancedUser.tenantId;
            session.user.tenantSlug = enhancedUser.organization.slug;
            session.user.status = enhancedUser.status;
            session.user.roles = enhancedUser.roles;
            session.user.personas = enhancedUser.personas;
            session.user.permissions = enhancedUser.permissions;
            session.user.activePersona = enhancedUser.activePersona;

            // Update last login
            await authService.updateLastLogin(user.id);
          }
        }

        return session;
      } catch (error) {
        console.error("Session callback error:", error);
        return session;
      }
    },

    // JWT callback - customize JWT token
    async jwt({ token, user, account, profile }) {
      // Initial sign in
      if (account && user) {
        token.userId = user.id;
        token.tenantId = user.tenantId;
        token.provider = account.provider;
      }

      // Return previous token if the access token has not expired yet
      return token;
    }
  },

  // Events for logging and monitoring
  events: {
    async signIn({ user, account, profile, isNewUser }) {
      await auditService.logAuthEvent({
        eventType: "signin",
        userId: user.id,
        tenantId: user.tenantId,
        provider: account?.provider || "unknown",
        isNewUser
      });

      // Initialize default persona for new users
      if (isNewUser) {
        await personaService.initializeDefaultPersonas(user.id, user.tenantId);
      }
    },

    async signOut({ token, session }) {
      if (session?.user?.id) {
        await auditService.logAuthEvent({
          eventType: "signout",
          userId: session.user.id,
          tenantId: session.user.tenantId
        });

        // Clean up session context
        await authService.cleanupSessionContext(session.user.id);
      }
    },

    async createUser({ user }) {
      await auditService.logAuthEvent({
        eventType: "user_created",
        userId: user.id,
        tenantId: user.tenantId,
        email: user.email
      });

      // Send welcome email
      await authService.sendWelcomeEmail(user.email!, user.name);
    },

    async linkAccount({ user, account, profile }) {
      await auditService.logAuthEvent({
        eventType: "account_linked",
        userId: user.id,
        tenantId: user.tenantId,
        provider: account.provider
      });
    },

    async session({ session, token }) {
      // Update session activity
      if (session.user?.id) {
        await authService.updateSessionActivity(session.user.id);
      }
    }
  },

  // Debug configuration
  debug: process.env.NODE_ENV === "development",

  // Logger configuration
  logger: {
    error: (code, metadata) => {
      console.error(`NextAuth Error [${code}]:`, metadata);

      // Log critical authentication errors
      auditService.logSecurityEvent({
        eventType: "nextauth_error",
        severity: "error",
        details: { code, metadata }
      });
    },
    warn: (code, metadata) => {
      console.warn(`NextAuth Warning [${code}]:`, metadata);
    },
    debug: (code, metadata) => {
      if (process.env.NODE_ENV === "development") {
        console.debug(`NextAuth Debug [${code}]:`, metadata);
      }
    }
  },

  // Custom theme
  theme: {
    colorScheme: "auto",
    brandColor: "#2563eb", // Skidspace brand blue
    logo: "/images/logo.svg",
    buttonText: "#ffffff"
  }
};

export default nextAuthOptions;