/**
 * Cached RBAC Functions with Proper Cache Management
 * Replaces direct React cache() usage with managed cache invalidation
 * Generated by Claude Code - 2026-04-06
 */

import { prisma } from './prisma'
import { unstable_cache } from 'next/cache'
import {
  CACHE_TAGS,
  CACHE_TTL,
  createCachedFunction,
  CacheHealthMonitor,
  RBACCacheManager
} from './rbac-cache'

export interface UserRole {
  id: string
  name: string
  slug: string
  level: number
  organizationId?: string
  resourceType?: string
  resourceId?: string
}

export interface UserPermission {
  slug: string
  category: string
  constraints?: any
}

/**
 * Get all roles for a user across all contexts (with proper cache management)
 */
export const getUserRoles = createCachedFunction(
  async (userId: string): Promise<UserRole[]> => {
    CacheHealthMonitor.recordCacheMiss(`getUserRoles-${userId}`)

    const userRoles = await prisma.userRole.findMany({
      where: { userId },
      include: {
        role: {
          include: {
            organization: true
          }
        }
      }
    })

    return userRoles.map(ur => ({
      id: ur.role.id,
      name: ur.role.name,
      slug: ur.role.slug,
      level: ur.role.level,
      organizationId: ur.role.organizationId || undefined,
      resourceType: ur.resourceType || undefined,
      resourceId: ur.resourceId || undefined
    }))
  },
  {
    tags: (userId: string) => [CACHE_TAGS.USER_ROLES(userId)],
    ttl: CACHE_TTL.ROLES,
    keyGenerator: (userId: string) => `user-roles-${userId}`
  }
)

/**
 * Get all permission slugs for a user (with proper cache management)
 */
export const getUserPermissions = createCachedFunction(
  async (userId: string): Promise<string[]> => {
    CacheHealthMonitor.recordCacheMiss(`getUserPermissions-${userId}`)

    const userRoles = await prisma.userRole.findMany({
      where: { userId },
      include: {
        role: {
          include: {
            permissions: {
              include: {
                permission: true
              }
            }
          }
        }
      }
    })

    const permissions = new Set<string>()

    userRoles.forEach(ur => {
      ur.role.permissions.forEach(rp => {
        if (rp.granted) { // Only include granted permissions
          permissions.add(rp.permission.slug)
        }
      })
    })

    return Array.from(permissions)
  },
  {
    tags: (userId: string) => [CACHE_TAGS.USER_PERMISSIONS(userId)],
    ttl: CACHE_TTL.PERMISSIONS,
    keyGenerator: (userId: string) => `user-permissions-${userId}`
  }
)

/**
 * Check if user has a specific permission (with context-aware caching)
 */
export const userHasPermission = createCachedFunction(
  async (
    userId: string,
    permissionSlug: string,
    context?: {
      organizationId?: string
      resourceType?: string
      resourceId?: string
    }
  ): Promise<boolean> => {
    const contextKey = context ? JSON.stringify(context) : 'global'
    CacheHealthMonitor.recordCacheMiss(`userHasPermission-${userId}-${permissionSlug}-${contextKey}`)

    const userRoles = await prisma.userRole.findMany({
      where: {
        userId,
        ...(context?.organizationId ? {
          role: { organizationId: context.organizationId }
        } : {}),
        ...(context?.resourceType ? { resourceType: context.resourceType } : {}),
        ...(context?.resourceId ? { resourceId: context.resourceId } : {})
      },
      include: {
        role: {
          include: {
            permissions: {
              include: {
                permission: true
              }
            }
          }
        }
      }
    })

    return userRoles.some(ur =>
      ur.role.permissions.some(rp =>
        rp.granted && rp.permission.slug === permissionSlug
      )
    )
  },
  {
    tags: (userId: string, permissionSlug: string, context?: any) => [
      CACHE_TAGS.USER_PERMISSIONS(userId),
      ...(context?.organizationId ? [CACHE_TAGS.ORGANIZATION_ROLES(context.organizationId)] : [])
    ],
    ttl: CACHE_TTL.PERMISSIONS,
    keyGenerator: (userId: string, permissionSlug: string, context?: any) =>
      `user-permission-${userId}-${permissionSlug}-${context ? JSON.stringify(context) : 'global'}`
  }
)

/**
 * Check if user has any of the specified permissions
 */
export const userHasAnyPermission = async (
  userId: string,
  permissionSlugs: string[],
  context?: {
    organizationId?: string
    resourceType?: string
    resourceId?: string
  }
): Promise<boolean> => {
  // Use Promise.all for parallel checking with cached functions
  const permissionChecks = await Promise.all(
    permissionSlugs.map(permission =>
      userHasPermission(userId, permission, context)
    )
  )

  return permissionChecks.some(hasPermission => hasPermission)
}

/**
 * Check if user has a specific role (with proper cache management)
 */
export const userHasRole = createCachedFunction(
  async (
    userId: string,
    roleSlug: string,
    context?: {
      organizationId?: string
      resourceType?: string
      resourceId?: string
    }
  ): Promise<boolean> => {
    const contextKey = context ? JSON.stringify(context) : 'global'
    CacheHealthMonitor.recordCacheMiss(`userHasRole-${userId}-${roleSlug}-${contextKey}`)

    const userRole = await prisma.userRole.findFirst({
      where: {
        userId,
        role: { slug: roleSlug },
        ...(context?.organizationId ? {
          role: { organizationId: context.organizationId }
        } : {}),
        ...(context?.resourceType ? { resourceType: context.resourceType } : {}),
        ...(context?.resourceId ? { resourceId: context.resourceId } : {})
      }
    })

    return !!userRole
  },
  {
    tags: (userId: string, roleSlug: string, context?: any) => [
      CACHE_TAGS.USER_ROLES(userId),
      ...(context?.organizationId ? [CACHE_TAGS.ORGANIZATION_ROLES(context.organizationId)] : [])
    ],
    ttl: CACHE_TTL.ROLES,
    keyGenerator: (userId: string, roleSlug: string, context?: any) =>
      `user-role-${userId}-${roleSlug}-${context ? JSON.stringify(context) : 'global'}`
  }
)

/**
 * Get user's highest role level (with proper cache management)
 */
export const getUserMaxRoleLevel = createCachedFunction(
  async (
    userId: string,
    organizationId?: string
  ): Promise<number> => {
    CacheHealthMonitor.recordCacheMiss(`getUserMaxRoleLevel-${userId}-${organizationId || 'global'}`)

    const userRoles = await prisma.userRole.findMany({
      where: {
        userId,
        ...(organizationId ? {
          role: { organizationId }
        } : {})
      },
      include: { role: true }
    })

    return Math.max(...userRoles.map(ur => ur.role.level), 0)
  },
  {
    tags: (userId: string, organizationId?: string) => [
      CACHE_TAGS.USER_ROLES(userId),
      ...(organizationId ? [CACHE_TAGS.ORGANIZATION_ROLES(organizationId)] : [])
    ],
    ttl: CACHE_TTL.ROLES,
    keyGenerator: (userId: string, organizationId?: string) =>
      `user-max-role-level-${userId}-${organizationId || 'global'}`
  }
)

/**
 * Check if user can perform action on another user (based on role hierarchy)
 */
export const canManageUser = async (
  actorUserId: string,
  targetUserId: string,
  organizationId?: string
): Promise<boolean> => {
  const [actorLevel, targetLevel] = await Promise.all([
    getUserMaxRoleLevel(actorUserId, organizationId),
    getUserMaxRoleLevel(targetUserId, organizationId)
  ])

  return actorLevel > targetLevel
}

/**
 * Get all users that a user can manage (based on role hierarchy)
 */
export const getManageableUsers = createCachedFunction(
  async (
    userId: string,
    organizationId?: string
  ) => {
    CacheHealthMonitor.recordCacheMiss(`getManageableUsers-${userId}-${organizationId || 'global'}`)

    const userLevel = await getUserMaxRoleLevel(userId, organizationId)

    const manageableUsers = await prisma.user.findMany({
      where: {
        ...(organizationId ? { organizationId } : {}),
        userRoles: {
          some: {
            role: {
              level: { lt: userLevel }
            }
          }
        }
      },
      include: {
        organization: true,
        userRoles: {
          include: { role: true }
        }
      }
    })

    return manageableUsers
  },
  {
    tags: (userId: string, organizationId?: string) => [
      CACHE_TAGS.USER_ROLES(userId),
      ...(organizationId ? [CACHE_TAGS.ORGANIZATION_ROLES(organizationId)] : [])
    ],
    ttl: CACHE_TTL.ROLES,
    keyGenerator: (userId: string, organizationId?: string) =>
      `manageable-users-${userId}-${organizationId || 'global'}`
  }
)

/**
 * Assign role to user (with cache invalidation)
 */
export async function assignRoleToUser(
  userId: string,
  roleId: string,
  assignedBy: string,
  context?: {
    resourceType?: string
    resourceId?: string
    expiresAt?: Date
  }
) {
  // Check if role assignment already exists
  const existing = await prisma.userRole.findFirst({
    where: {
      userId,
      roleId,
      resourceType: context?.resourceType || null,
      resourceId: context?.resourceId || null
    }
  })

  if (existing) {
    throw new Error('Role already assigned to user')
  }

  // Create the assignment
  const userRole = await prisma.userRole.create({
    data: {
      userId,
      roleId,
      assignedBy,
      resourceType: context?.resourceType,
      resourceId: context?.resourceId,
      expiresAt: context?.expiresAt
    },
    include: {
      role: true,
      user: true
    }
  })

  // Invalidate relevant caches
  await RBACCacheManager.invalidateUserCache(userId)

  // Also invalidate organization cache if applicable
  if (userRole.user.organizationId) {
    await RBACCacheManager.invalidateOrganizationCache(userRole.user.organizationId, [userId])
  }

  // Log the assignment
  await prisma.auditLog.create({
    data: {
      userId: assignedBy,
      organizationId: userRole.user.organizationId,
      action: 'role.assign',
      resource: `user:${userId}`,
      details: {
        roleId,
        roleName: userRole.role.name,
        targetUserId: userId,
        resourceType: context?.resourceType,
        resourceId: context?.resourceId,
        cacheInvalidated: true // Track cache invalidation
      },
      status: 'success'
    }
  })

  return userRole
}

/**
 * Remove role from user (with cache invalidation)
 */
export async function removeRoleFromUser(
  userId: string,
  roleId: string,
  removedBy: string,
  context?: {
    resourceType?: string
    resourceId?: string
  }
) {
  const userRole = await prisma.userRole.findFirst({
    where: {
      userId,
      roleId,
      resourceType: context?.resourceType || null,
      resourceId: context?.resourceId || null
    },
    include: {
      role: true,
      user: true
    }
  })

  if (!userRole) {
    throw new Error('Role assignment not found')
  }

  await prisma.userRole.delete({
    where: { id: userRole.id }
  })

  // Invalidate relevant caches
  await RBACCacheManager.invalidateUserCache(userId)

  // Also invalidate organization cache if applicable
  if (userRole.user.organizationId) {
    await RBACCacheManager.invalidateOrganizationCache(userRole.user.organizationId, [userId])
  }

  // Log the removal
  await prisma.auditLog.create({
    data: {
      userId: removedBy,
      organizationId: userRole.user.organizationId,
      action: 'role.remove',
      resource: `user:${userId}`,
      details: {
        roleId,
        roleName: userRole.role.name,
        targetUserId: userId,
        resourceType: context?.resourceType,
        resourceId: context?.resourceId,
        cacheInvalidated: true // Track cache invalidation
      },
      status: 'success'
    }
  })

  return userRole
}

/**
 * Organization-specific permission checker for multi-tenant context
 */
export const checkOrganizationPermission = async (
  userId: string,
  permissionSlug: string,
  organizationId: string
): Promise<boolean> => {
  // Check for platform-wide permissions (super admin)
  const platformPermission = await userHasPermission(userId, permissionSlug)
  if (platformPermission) return true

  // Check for organization-specific permissions
  return userHasPermission(userId, permissionSlug, { organizationId })
}

/**
 * Warehouse-specific permission checker
 */
export const checkWarehousePermission = createCachedFunction(
  async (
    userId: string,
    permissionSlug: string,
    warehouseId: string
  ): Promise<boolean> => {
    CacheHealthMonitor.recordCacheMiss(`checkWarehousePermission-${userId}-${permissionSlug}-${warehouseId}`)

    // Check warehouse access
    const warehouseAccess = await prisma.warehouseAccess.findFirst({
      where: {
        userId,
        warehouseId
      },
      include: {
        warehouse: true
      }
    })

    if (!warehouseAccess) return false

    // Check organization-level permission
    return checkOrganizationPermission(
      userId,
      permissionSlug,
      warehouseAccess.warehouse.organizationId
    )
  },
  {
    tags: (userId: string, permissionSlug: string, warehouseId: string) => [
      CACHE_TAGS.USER_PERMISSIONS(userId),
      CACHE_TAGS.WAREHOUSE_ACCESS(userId)
    ],
    ttl: CACHE_TTL.WAREHOUSE_ACCESS,
    keyGenerator: (userId: string, permissionSlug: string, warehouseId: string) =>
      `warehouse-permission-${userId}-${permissionSlug}-${warehouseId}`
  }
)

/**
 * Get user's accessible warehouses
 */
export const getUserWarehouses = createCachedFunction(
  async (userId: string) => {
    CacheHealthMonitor.recordCacheMiss(`getUserWarehouses-${userId}`)

    const warehouseAccess = await prisma.warehouseAccess.findMany({
      where: { userId },
      include: {
        warehouse: {
          include: {
            organization: true
          }
        }
      }
    })

    return warehouseAccess.map(wa => ({
      ...wa.warehouse,
      accessLevel: wa.accessLevel
    }))
  },
  {
    tags: (userId: string) => [CACHE_TAGS.WAREHOUSE_ACCESS(userId)],
    ttl: CACHE_TTL.WAREHOUSE_ACCESS,
    keyGenerator: (userId: string) => `user-warehouses-${userId}`
  }
)

/**
 * Organization membership checker
 */
export const isOrganizationMember = createCachedFunction(
  async (
    userId: string,
    organizationId: string
  ): Promise<boolean> => {
    CacheHealthMonitor.recordCacheMiss(`isOrganizationMember-${userId}-${organizationId}`)

    const user = await prisma.user.findFirst({
      where: {
        id: userId,
        organizationId
      }
    })

    return !!user
  },
  {
    tags: (userId: string, organizationId: string) => [
      CACHE_TAGS.USER_ROLES(userId),
      CACHE_TAGS.ORGANIZATION_ROLES(organizationId)
    ],
    ttl: CACHE_TTL.ROLES,
    keyGenerator: (userId: string, organizationId: string) =>
      `org-membership-${userId}-${organizationId}`
  }
)