/**
 * RBAC Cache Management System
 * Addresses cache consistency issues in React RBAC implementation
 * Generated by Claude Code - 2026-04-06
 */

import { unstable_cache, revalidateTag } from 'next/cache'

// Cache tags for fine-grained invalidation
export const CACHE_TAGS = {
  USER_ROLES: (userId: string) => `user-roles-${userId}`,
  USER_PERMISSIONS: (userId: string) => `user-permissions-${userId}`,
  ORGANIZATION_ROLES: (orgId: string) => `org-roles-${orgId}`,
  ROLE_PERMISSIONS: (roleId: string) => `role-permissions-${roleId}`,
  USER_SESSION: (userId: string) => `user-session-${userId}`,
  WAREHOUSE_ACCESS: (userId: string) => `warehouse-access-${userId}`,
} as const

// Cache TTL settings (in seconds)
export const CACHE_TTL = {
  ROLES: 300, // 5 minutes
  PERMISSIONS: 300, // 5 minutes
  SESSION: 60, // 1 minute
  WAREHOUSE_ACCESS: 600, // 10 minutes
} as const

/**
 * Cache invalidation utilities
 */
export class RBACCacheManager {
  /**
   * Invalidate user-specific caches when roles change
   */
  static async invalidateUserCache(userId: string): Promise<void> {
    const tags = [
      CACHE_TAGS.USER_ROLES(userId),
      CACHE_TAGS.USER_PERMISSIONS(userId),
      CACHE_TAGS.USER_SESSION(userId),
      CACHE_TAGS.WAREHOUSE_ACCESS(userId),
    ]

    await Promise.all(tags.map(tag => revalidateTag(tag)))
  }

  /**
   * Invalidate organization-wide caches when org structure changes
   */
  static async invalidateOrganizationCache(organizationId: string, affectedUserIds?: string[]): Promise<void> {
    const tags = [CACHE_TAGS.ORGANIZATION_ROLES(organizationId)]

    // Also invalidate affected users
    if (affectedUserIds) {
      affectedUserIds.forEach(userId => {
        tags.push(
          CACHE_TAGS.USER_ROLES(userId),
          CACHE_TAGS.USER_PERMISSIONS(userId),
          CACHE_TAGS.USER_SESSION(userId)
        )
      })
    }

    await Promise.all(tags.map(tag => revalidateTag(tag)))
  }

  /**
   * Invalidate role-specific caches when role permissions change
   */
  static async invalidateRoleCache(roleId: string, affectedUserIds?: string[]): Promise<void> {
    const tags = [CACHE_TAGS.ROLE_PERMISSIONS(roleId)]

    // Invalidate all users with this role
    if (affectedUserIds) {
      affectedUserIds.forEach(userId => {
        tags.push(
          CACHE_TAGS.USER_PERMISSIONS(userId),
          CACHE_TAGS.USER_SESSION(userId)
        )
      })
    }

    await Promise.all(tags.map(tag => revalidateTag(tag)))
  }

  /**
   * Clear all RBAC caches (use sparingly)
   */
  static async clearAllCaches(): Promise<void> {
    // This is a nuclear option - consider using specific invalidation instead
    const patterns = ['user-roles-', 'user-permissions-', 'org-roles-', 'role-permissions-', 'user-session-', 'warehouse-access-']

    // Note: Next.js doesn't support pattern-based invalidation, so this is a conceptual implementation
    // In practice, you'd need to track active cache keys or use a different caching strategy
    console.warn('clearAllCaches called - consider using specific cache invalidation instead')
  }

  /**
   * Preload commonly accessed permissions into cache
   */
  static async preloadUserCaches(userId: string): Promise<void> {
    try {
      // Import the cached functions to trigger preloading
      const { getUserRoles, getUserPermissions } = await import('./rbac-cached')

      // Fire and forget preload
      Promise.all([
        getUserRoles(userId),
        getUserPermissions(userId),
      ]).catch(error => {
        console.warn('Cache preload failed:', error)
      })
    } catch (error) {
      console.warn('Cache preload import failed:', error)
    }
  }
}

/**
 * Cached function factory with consistent tagging
 */
export function createCachedFunction<T extends any[], R>(
  fn: (...args: T) => Promise<R>,
  options: {
    tags: ((...args: T) => string[])
    ttl?: number
    keyGenerator?: (...args: T) => string
  }
) {
  return unstable_cache(
    fn,
    options.keyGenerator ? undefined : [(fn as any).name],
    {
      tags: options.tags as any,
      revalidate: options.ttl || CACHE_TTL.ROLES,
    }
  )
}

/**
 * Cache warming utilities for test environments
 */
export class TestCacheManager {
  /**
   * Clear test caches to ensure clean state
   */
  static async clearTestCaches(): Promise<void> {
    // In test environment, we need to ensure clean cache state
    if (process.env.NODE_ENV === 'test') {
      await RBACCacheManager.clearAllCaches()
    }
  }

  /**
   * Warm cache for test scenarios
   */
  static async warmTestCache(testData: { userId: string; organizationId?: string }): Promise<void> {
    if (process.env.NODE_ENV === 'test') {
      await RBACCacheManager.preloadUserCaches(testData.userId)
    }
  }
}

/**
 * Cache health monitoring
 */
export class CacheHealthMonitor {
  private static cacheHits = new Map<string, number>()
  private static cacheMisses = new Map<string, number>()

  static recordCacheHit(cacheKey: string): void {
    this.cacheHits.set(cacheKey, (this.cacheHits.get(cacheKey) || 0) + 1)
  }

  static recordCacheMiss(cacheKey: string): void {
    this.cacheMisses.set(cacheKey, (this.cacheMisses.get(cacheKey) || 0) + 1)
  }

  static getCacheStats(): { hits: number; misses: number; ratio: number } {
    const totalHits = Array.from(this.cacheHits.values()).reduce((sum, count) => sum + count, 0)
    const totalMisses = Array.from(this.cacheMisses.values()).reduce((sum, count) => sum + count, 0)

    return {
      hits: totalHits,
      misses: totalMisses,
      ratio: totalHits / (totalHits + totalMisses) || 0
    }
  }

  static resetStats(): void {
    this.cacheHits.clear()
    this.cacheMisses.clear()
  }
}